trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"

  - task: Npm@1
    displayName: "Install NPM packages"
    inputs:
      command: "install"

  - task: Npm@1
    displayName: "Run tests"
    inputs:
      command: "custom"
      customCommand: "run test"

  - script: |
      git config --global user.email "ucdotnetadmin@ucdavis.edu"
      git config --global user.name "Azure Pipeline"
    displayName: "Configure git identity"
    
  - task: Npm@1
    displayName: "Update patch number"
    inputs:
      command: "custom"
      customCommand: "version patch --force"

  - task: Npm@1
    displayName: "Publish to npmjs"
    inputs:
      command: publish
      publishRegistry: useExternalRegistry
      publishEndpoint: "npmjs.org"

  - script: |
      git push -u origin HEAD:main
    displayName: "Push to git origin"