name: $(majorMinorVersion).$(semanticVersion)

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"

  - task: Npm@1
    displayName: "Install Npm Packages"
    inputs:
      command: "install"
      workingDir: "./"

  - task: Npm@1
    displayName: "Run Tests"
    inputs:
      command: "custom"
      workingDir: "./"
      customCommand: "run test"

  # - task: Npm@1
  #   inputs:
  #     command: publish
  #     publishRegistry: useExternalRegistry
  #     publishEndpoint: "npmjs.org"
